# 8 m5.2xlarge nodes --> 64 CPUs
head_node_type:
  name: head_node_type
  instance_type: m5.2xlarge

worker_node_types:
- name: cpu_worker
  instance_type: m5.2xlarge
  min_worker_nodes: 7
  max_worker_nodes: 7
  use_spot: false
